#!/usr/bin/env python3
"""
Snapshot the Diana source into backups/working-<timestamp>/ so there is always a
known-good restore point. Source only (src, platformio.ini, tools, sdcard, partitions,
README) - the .pio build folder is excluded because `pio run` regenerates it.

  python tools/backup.py                 # timestamped snapshot
  python tools/backup.py "voice fix"     # timestamped snapshot with a label in the folder name

Restore later by copying a snapshot's src\ back over the project's src\, then `pio run`.
"""
import os, sys, shutil, datetime, re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INCLUDE = ["src", "platformio.ini", "tools", "sdcard", "partitions", "README.md"]

def main():
    label = ""
    if len(sys.argv) > 1:
        label = "-" + re.sub(r"[^A-Za-z0-9_-]+", "-", sys.argv[1].strip()).strip("-")
    stamp = datetime.datetime.now().strftime("%Y-%m-%d_%H%M")
    dest = os.path.join(ROOT, "backups", f"working-{stamp}{label}")
    if os.path.exists(dest):
        dest += "-2"
    os.makedirs(dest, exist_ok=True)

    for item in INCLUDE:
        src = os.path.join(ROOT, item)
        if not os.path.exists(src):
            continue
        dst = os.path.join(dest, item)
        if os.path.isdir(src):
            shutil.copytree(src, dst, dirs_exist_ok=True)
        else:
            shutil.copyfile(src, dst)

    note = (
        "DIANA CARDPUTER RESTORE POINT\n"
        f"created: {datetime.datetime.now().isoformat(timespec='seconds')}\n"
        f"label:   {sys.argv[1] if len(sys.argv) > 1 else '(none)'}\n\n"
        "Source-only snapshot. To restore, from the project root copy this snapshot's src\\ back:\n"
        f"  PowerShell:  Copy-Item -Recurse -Force \"{os.path.relpath(dest, ROOT)}\\src\" .\n"
        "then rebuild + flash:\n"
        "  pio run\n"
        "  pio run -t upload --upload-port COM3\n"
        "(.pio build folder is not saved - it is regenerated by `pio run`.)\n"
    )
    with open(os.path.join(dest, "RESTORE.txt"), "w", encoding="utf-8") as f:
        f.write(note)

    # count file size
    total = sum(os.path.getsize(os.path.join(dp, f)) for dp, _, fs in os.walk(dest) for f in fs)
    print(f"backup created: {os.path.relpath(dest, ROOT)}  ({total/1024/1024:.1f} MB)")
    # list existing restore points
    bdir = os.path.join(ROOT, "backups")
    pts = sorted(d for d in os.listdir(bdir) if os.path.isdir(os.path.join(bdir, d)))
    print(f"restore points now ({len(pts)}):")
    for d in pts:
        print("  -", d)

if __name__ == "__main__":
    main()
